name: default_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  zoom_tap_animation: ^1.1.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  intl: ^0.19.0
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sriracha
      fonts:
        - asset: assets/fonts/Sriracha/Sriracha-Regular.ttf
          style: italic